config/routes.rb
RailsOnWeb::Application.routes.draw do
  get 'product_cates/page/:page', to: 'product_cates#index'
  get 'product_cates/:id/page/:page', to: 'product_cates#show'
  get 'product_items/page/:page', to: 'product_items#index'
  get 'news_cates/page/:page', to: 'news_cates#index'
  
  get 'pages/page/:page', to: 'pages#index'
  
  resources :tags

  resources :contacts

  resources :comments

  resources :shops

  resources :resource_items

  resources :resource_cates

  resources :product_items, :except => :index

  resources :product_cates, :only => [:index, :show]

  resources :news_items, :except => :index
  get 'news_items/(page/:page)', to: 'news_items#index'
  
  get "news_cates/:id(/pages/:page)" => "news_cates#show", :as => :news_cates
  resources :news_cates, :only => [:index, :show]
  

  get "home/happy_teachers_day"
  get "home/index"
  get "home/search"
  get "home/form"
  get "home/location"
  get "home/site_map"
  get "home/get_cdhrss"
  get "home/start_sidekiq_cd12333"
  get "home/start_sidekiq_sina_news"
  get "home/start_sidekiq_china_insurance"

  match "form" => "home#form"
  match "search" => "home#search"
  
  match "upload" => "resource_items#upload"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :pages
  match "/en/:id" => "pages#en"

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/news_cate.rb
class NewsCate < ActiveRecord::Base
  has_many :news_items

  before_save :translate_en
  after_save :expire_cate_cache
  self.per_page = 10
  
  def translate_en
    self.en_name = Pinyin.t self.name
    self.en_name = self.en_name.gsub(/\s+/, '-')
  end

  def expire_cate_cache
    cache_index_path = File.join(Rails.root, 'public', 'index.html')
    cache_cate_path = File.join(Rails.root, 'public', 'news_cates', self.en_name + '.html')
    cache_cate_path2 = File.join(Rails.root, 'public', 'news_cates', self.id.to_s + '.html')
    cache_cate_dir = File.join(Rails.root, 'public', 'news_cates', self.en_name)
    FileUtils.rm_rf cache_index_path if File.exist?(cache_index_path)
    FileUtils.rm_rf cache_cate_path if File.exist?(cache_cate_path)
    FileUtils.rm_rf cache_cate_path2 if File.exist?(cache_cate_path2)
    FileUtils.rm_rf cache_cate_dir if File.exist?(cache_cate_dir)
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :news_cate
  after_save :expire_cache
  after_create :expire_cate_cache, :count_news, :assign_original_url
  self.per_page = 50
  
  def self.recent(count, cate = 0, image = false)
    conditions = cate > 0 ? "news_cate_id = #{cate}" : "true"
    conditions += " AND image_path IS NOT NULL" if image
    NewsItem.where(conditions).order("updated_at DESC").limit(count)
  end

  #if id = 1 return 1..9
  #if id = 5 return 1..10
  #if id = 7 return 2..12
  def self.recent_related(id)
    low = id > 10 ? id-10 : 1
    height = id > 20 ? id + 10 : id + (20 - id)
    NewsItem.where("id in(#{(low..height).to_a.join(',')})").order("id desc")
  end
  
  def expire_cache
    cache_path = File.join(Rails.root, 'public', 'news_items', self.id.to_s + '.html')
    FileUtils.rm_rf cache_path if File.exist?(cache_path)
  end

  def expire_cate_cache
    cache_index_path = File.join(Rails.root, 'public', 'index.html')
    cache_cate_path = File.join(Rails.root, 'public', 'news_cates', self.news_cate.en_name + '.html')
    cache_cate_path2 = File.join(Rails.root, 'public', 'news_cates', self.id.to_s + '.html')
    cache_cate_dir = File.join(Rails.root, 'public', 'news_cates', self.news_cate.en_name)
    FileUtils.rm_rf cache_index_path if File.exist?(cache_index_path)
    FileUtils.rm_rf cache_cate_path if File.exist?(cache_cate_path)
    FileUtils.rm_rf cache_cate_path2 if File.exist?(cache_cate_path2)
    FileUtils.rm_rf cache_cate_dir if File.exist?(cache_cate_dir)
  end

  def count_news
    NewsCate.update(self.news_cate_id, :news_count => self.news_cate.news_items.size)
  end

  def assign_original_url
    return unless self.original_url.blank?
    self.original_url = "/news_items/#{self.id}"
    self.save!
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :page_parts

  def self.recent(count, menu_match = nil)
    if menu_match
      Page.where(:menu_match => menu_match).order("updated_at DESC").limit(count)
    else
      Page.order("updated_at DESC").limit(count)
    end
  end
end

app/models/page_part.rb
class PagePart < ActiveRecord::Base
  belongs_to :page
  belongs_to :part
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :page_parts
end

app/models/product_cate.rb
class ProductCate < ActiveRecord::Base
    has_many :product_items
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product_cate

  def self.recent(count, cate=nil)
    if cate
      ct = ProductCate.find_by_name(cate)
      return [] if ct.nil?
      return ct.product_items.order("updated_at DESC").limit(count)
    else
      ProductItem.order("updated_at DESC").limit(count)
    end
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/resource_cate.rb
class ResourceCate < ActiveRecord::Base
  has_many :recources_items
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  def self.recent(count)
    Tag.order("RAND()").limit(count)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/news_cates_controller.rb
#encoding: utf-8
class NewsCatesController < InheritedResources::Base
  before_filter :authenticate_admin_user!, :except => [:index, :show]
  caches_page :index, :show
  before_filter(only: [:index, :show]) { @page_caching = true }
  cache_sweeper :news_cate_sweeper

  def show
    @news_cate = params[:id] =~ /^\d+$/ ? NewsCate.find_by_id(params[:id]) : (NewsCate.find_by_en_name(params[:id]) || NewsCate.find_by_en_name(params[:id].gsub(/-/, ' ')))
    @news_cate ||= NewsCate.find(1)
    @news_items = @news_cate.news_items.order('updated_at DESC').paginate(:page => params[:page] || 1)
    #setup workers one day a time
    Cd12333Worker.perform_async if @news_cate.id == 80 && (Time.now - (@news_cate.updated_at.blank? ? Time.new("1000-01-01") : @news_cate.updated_at)) > 86400 && request.host != 'localhost'
    CdhrssWorker.perform_async if ['保险成都', '成都人社局'].include?(@news_cate.name) && (Time.now - (@news_cate.updated_at.blank? ? Time.new("1000-01-01") : @news_cate.updated_at)) > 86400 && request.host != 'localhost'
    SinaNewsWorker.perform_async if (Time.now - (@news_cate.updated_at.blank? ? Time.new("1000-01-01") : @news_cate.updated_at)) > 86400 && request.host != 'localhost'
    ChinaInsuranceWorker.perform_async if (Time.now - (@news_cate.updated_at.blank? ? Time.new("1000-01-01") : @news_cate.updated_at)) > 86400 && request.host != 'localhost'
  
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_cates_helper.rb
module NewsCatesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/news_cates/_form.html.erb
<%= form_for(@news_cate) do |f| %>
  <% if @news_cate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_cate.errors.count, "error") %> prohibited this news_cate from being saved:</h2>

      <ul>
      <% @news_cate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_cates/edit.html.erb
<h1>Editing news_cate</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_cate %> |
<%= link_to 'Back', news_cates_path %>

app/views/news_cates/index.html.erb
<% title ["保险信息列表", "成都保险咨询网，投保好帮手！"].join(',') %>
<% meta_keywords ["保险,保险网,买保险,网上买保险,在线投保,成都保险咨询网,成都保险,商业保险,人寿保险"].join(',') %>
<% meta_description ["成都保险咨询网是成都地区最专业的保险网，设有人寿保险,少儿保险,医疗保险,平安人寿,平安车险，保险投保案例,保险咨询问答,保险博客等栏目，为您提供保险产品的咨询购买理赔保全一站式服务！是您投保的好帮手！咨询QQ：29928649"].join(',') %>

<h1>信息分类</h1>

<table>

<% @news_cates.each do |news_cate| %>
  <tr>
    <td><%= news_cate.name %></td>
    <td><%= link_to '查看', news_cate %></td>
  </tr>
<% end %>
</table>

app/views/news_cates/new.html.erb
<h1>New news_cate</h1>

<%= render 'form' %>

<%= link_to 'Back', news_cates_path %>

app/views/news_cates/show.html.erb
<% title [@news_cate.name, "成都保险咨询网，投保好帮手！"].join(',') %>
<% meta_keywords [@news_cate.name, "保险,保险网,买保险,网上买保险,在线投保,成都保险咨询网,成都保险,商业保险,人寿保险"].join(',') %>
<% meta_description [@news_cate.name, "成都保险咨询网是成都地区最专业的保险网，设有人寿保险,少儿保险,医疗保险,平安人寿,平安车险，保险投保案例,保险咨询问答,保险博客等栏目，为您提供保险产品的咨询购买理赔保全一站式服务！是您投保的好帮手！咨询QQ：29928649"].join('-') %>


<% items3 = [] %>
<% 3.times{|i| items3 << @news_items.shift} %>
<% items1, items2 = @news_items.partition{|i| i.id%2 ==  0} %>

<ul class="category">
 <% items3.each do |item| %>
     <li class="level_1">
        <h3><%= link_to item.title, news_item_path(item), :target => "_blank", :title => item.title%></h3>
        <div class="level_2">
            <% content = item.summary.blank? ? item.body : item.summary %>
            <%=  strip_tags(content).to_s.gsub(/[ ]+|\s+|\t+|\n+/, '').truncate(200)%>
            <i><%=item.updated_at.blank? ? Time.now.strftime("(%Y-%m-%d)") : item.updated_at.strftime("(%Y-%m-%d)")  %></i>
        </div>
    </li>
 <% end %>
</ul>

<div style="width: 100%; position: relative;">
    <div style="width: 350px; float: left; margin-right: 10px;">
<ul class="category">
 <% items1.each_with_index do |item, index| %>
   <li class="level_1"><%= link_to item.title, news_item_path(item), :target => "_blank", :title => item.title%>
    <i><%=item.updated_at.blank? ? Time.now.strftime("(%Y-%m-%d)") : item.updated_at.strftime("(%Y-%m-%d)")  %></i>
   </li>
   <%if index%5== 0 %>
     <br>
   <% end %>
 <% end %>
</ul>

<div class="cate_banner">
    <%= cate_banner @news_cate.name %>
</div>

</div>
<div style="margin-left: 360px;">
<ul class="category">
 <% items2.each_with_index do |item, index| %>
   <li class="level_1"><%= link_to item.title, news_item_path(item), :target => "_blank", :title => item.title%>
      <i><%=item.updated_at.blank? ? Time.now.strftime("(%Y-%m-%d)") : item.updated_at.strftime("(%Y-%m-%d)")  %></i>
   </li>
   <%if index%5== 0 %>
     <br>
   <% end %>
 <% end %>
</ul>
</div>
</div>


<div style="display: block; width: 600px; float: left;">
 <%=will_paginate @news_items, :next_label => "下一页", :prev_label => "上一页"%>
 
  <br/>
<%= render :partial => "layouts/bshare" %>
<br/>

</div>