config/routes.rb
RailsOnWeb::Application.routes.draw do
  get 'product_cates/page/:page', to: 'product_cates#index'
  get 'product_cates/:id/page/:page', to: 'product_cates#show'
  get 'product_items/page/:page', to: 'product_items#index'
  get 'news_cates/page/:page', to: 'news_cates#index'
  
  get 'pages/page/:page', to: 'pages#index'
  
  resources :tags

  resources :contacts

  resources :comments

  resources :shops

  resources :resource_items

  resources :resource_cates

  resources :product_items, :except => :index

  resources :product_cates, :only => [:index, :show]

  resources :news_items, :except => :index
  get 'news_items/(page/:page)', to: 'news_items#index'
  
  get "news_cates/:id(/pages/:page)" => "news_cates#show", :as => :news_cates
  resources :news_cates, :only => [:index, :show]
  

  get "home/happy_teachers_day"
  get "home/index"
  get "home/search"
  get "home/form"
  get "home/location"
  get "home/site_map"
  get "home/get_cdhrss"
  get "home/start_sidekiq_cd12333"
  get "home/start_sidekiq_sina_news"
  get "home/start_sidekiq_china_insurance"

  match "form" => "home#form"
  match "search" => "home#search"
  
  match "upload" => "resource_items#upload"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :pages
  match "/en/:id" => "pages#en"

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/news_cate.rb
class NewsCate < ActiveRecord::Base
  has_many :news_items

  before_save :translate_en
  after_save :expire_cate_cache
  self.per_page = 10
  
  def translate_en
    self.en_name = Pinyin.t self.name
    self.en_name = self.en_name.gsub(/\s+/, '-')
  end

  def expire_cate_cache
    cache_index_path = File.join(Rails.root, 'public', 'index.html')
    cache_cate_path = File.join(Rails.root, 'public', 'news_cates', self.en_name + '.html')
    cache_cate_path2 = File.join(Rails.root, 'public', 'news_cates', self.id.to_s + '.html')
    cache_cate_dir = File.join(Rails.root, 'public', 'news_cates', self.en_name)
    FileUtils.rm_rf cache_index_path if File.exist?(cache_index_path)
    FileUtils.rm_rf cache_cate_path if File.exist?(cache_cate_path)
    FileUtils.rm_rf cache_cate_path2 if File.exist?(cache_cate_path2)
    FileUtils.rm_rf cache_cate_dir if File.exist?(cache_cate_dir)
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :news_cate
  after_save :expire_cache
  after_create :expire_cate_cache, :count_news, :assign_original_url
  self.per_page = 50
  
  def self.recent(count, cate = 0, image = false)
    conditions = cate > 0 ? "news_cate_id = #{cate}" : "true"
    conditions += " AND image_path IS NOT NULL" if image
    NewsItem.where(conditions).order("updated_at DESC").limit(count)
  end

  #if id = 1 return 1..9
  #if id = 5 return 1..10
  #if id = 7 return 2..12
  def self.recent_related(id)
    low = id > 10 ? id-10 : 1
    height = id > 20 ? id + 10 : id + (20 - id)
    NewsItem.where("id in(#{(low..height).to_a.join(',')})").order("id desc")
  end
  
  def expire_cache
    cache_path = File.join(Rails.root, 'public', 'news_items', self.id.to_s + '.html')
    FileUtils.rm_rf cache_path if File.exist?(cache_path)
  end

  def expire_cate_cache
    cache_index_path = File.join(Rails.root, 'public', 'index.html')
    cache_cate_path = File.join(Rails.root, 'public', 'news_cates', self.news_cate.en_name + '.html')
    cache_cate_path2 = File.join(Rails.root, 'public', 'news_cates', self.id.to_s + '.html')
    cache_cate_dir = File.join(Rails.root, 'public', 'news_cates', self.news_cate.en_name)
    FileUtils.rm_rf cache_index_path if File.exist?(cache_index_path)
    FileUtils.rm_rf cache_cate_path if File.exist?(cache_cate_path)
    FileUtils.rm_rf cache_cate_path2 if File.exist?(cache_cate_path2)
    FileUtils.rm_rf cache_cate_dir if File.exist?(cache_cate_dir)
  end

  def count_news
    NewsCate.update(self.news_cate_id, :news_count => self.news_cate.news_items.size)
  end

  def assign_original_url
    return unless self.original_url.blank?
    self.original_url = "/news_items/#{self.id}"
    self.save!
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :page_parts

  def self.recent(count, menu_match = nil)
    if menu_match
      Page.where(:menu_match => menu_match).order("updated_at DESC").limit(count)
    else
      Page.order("updated_at DESC").limit(count)
    end
  end
end

app/models/page_part.rb
class PagePart < ActiveRecord::Base
  belongs_to :page
  belongs_to :part
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :page_parts
end

app/models/product_cate.rb
class ProductCate < ActiveRecord::Base
    has_many :product_items
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product_cate

  def self.recent(count, cate=nil)
    if cate
      ct = ProductCate.find_by_name(cate)
      return [] if ct.nil?
      return ct.product_items.order("updated_at DESC").limit(count)
    else
      ProductItem.order("updated_at DESC").limit(count)
    end
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/resource_cate.rb
class ResourceCate < ActiveRecord::Base
  has_many :recources_items
end

app/models/resource_item.rb
class ResourceItem < ActiveRecord::Base
  belongs_to :resource_cate
  attr_accessor :upload_file

  def self.type_hash
  	{1 => 'picture', 2 => 'file', 3 => 'video', 4 => 'audio', 5 => 'flash'}
  end

  def self.recent(count)
    ResourceItem.order("updated_at DESC").limit(count)
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  def self.recent(count)
    Tag.order("RAND()").limit(count)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base
  before_filter :authenticate_admin_user!, :except => [:index, :show]

  def show
    @tag = params[:id] =~ /\d+/ ? Tag.find_by_id(params[:id]) : Tag.find_by_name(params[:id])
    @tag ||= Tag.last

    #search from news_items
    @news_items = NewsItem.where("title regexp '#{@tag.name}'").paginate(:per_page => 40, :page => params[:page] || 1)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :meta_key %><br />
    <%= f.text_field :meta_key %>
  </div>
  <div class="field">
    <%= f.label :meta_description %><br />
    <%= f.text_field :meta_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<% title ["成都保险咨询"].join(' - ') %>
<% meta_keywords ["热门标签，成都商业保险咨询"].join(' - ') %>
<% meta_description ["成都保险，投保， 保险咨询，保险购买，商业保险，中国平安，网址：www.baoxian028.com"].join(' - ') %>


<div style="padding:20px;">
<h1>热门标签</h1>
<hr/>
<% @tags.each do |tag| %>
  <span class="tag"><%=link_to tag.name, tag, :title => tag.name, :class => "rand#{weight(tag.weight, 12)}", :target => "_blank"%></span>
<% end %>
</div>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<% title [@tag.name, "成都保险咨询网"].join('-') %>
<% meta_keywords [@tag.meta_key].join('-') %>
<% meta_description [@tag.meta_description].join('-') %>


<div style="padding:20px;">
<h2><%=link_to @tag.name, "/search?q=#{@tag.name}", :target => "_blank" %></h2>
<hr/>

<ul class="category">
<% unless @news_items.nil? %>
 <% @news_items.each do |item| %>
   <li class="level_1"><%= link_to item.title, news_item_path(item), :target => "_blank", :title => item.title%></li>
 <% end %>
<% end %>
</ul>
<br/>
<%= render :partial => "layouts/bshare" %>
<br/>
<%=will_paginate @news_items, :next_label => "下一页", :prev_label => "上一页"%>
</div>